require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['API/product/test_product.rb',
  'API/compared_products/test_compared_products.rb']
  t.verbose = true
end