require 'minitest/autorun'
require 'yaml'
require 'logger'
require 'cassandra'
require 'active_support'
require 'active_support/all'
require_relative '../../../lib/tools/Model/featured_new_product/featured_new_product'
require_relative '../../../lib/tools/Model/customer/customer'
require_relative '../../../lib/tools/Model/turbo_cluster'
ENV['TURBO_MODE'] = "test"
